@echo off
echo Starting GoalPath AI...
cd /d "C:\Users\workr\Downloads\AI-Learning-Project"
echo Activating virtual environment...
call .\venv\Scripts\activate.bat
echo Launching Streamlit app...
streamlit run app.py
pause
